# Variables
EXE=mnk-game

# Rules and targets
all: build

build:
	@cd src && $(MAKE)
	@mv -f src/$(EXE) .

clean:
	@cd src && $(MAKE) clean
	@rm -f $(EXE) *~

.PHONY: all build clean help

help:
	@echo "help mnk-game/src/:"
	@echo
	@echo "-------------------"
	@echo "  Usage  "
	@echo "-------------------"
	@echo " make [all] build the software"
	@echo " make clean Remove all files generated by make"
	@echo " make help Display this help"
	@echo "-------------------"
